site_name: Grading Notes
site_url: https://shabie.github.io/grading-notes
copyright: © 2024 Shabie
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md


markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

repo_name: shabie/grading-notes
repo_url: https://github.com/shabie/grading-notes